"""initial_schema

Revision ID: db30183c0752
Revises: 
Create Date: 2026-09-12 10:13:54.721920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db30183c0752'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sensor_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_key', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('normal_min', sa.Float(), nullable=False),
    sa.Column('normal_max', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_key')
    )
    op.create_table('elevators',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('building_id', sa.String(length=20), nullable=False),
    sa.Column('current_floor', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('active_fault', sa.String(length=200), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('load_percentage', sa.Float(), nullable=False),
    sa.Column('door_status', sa.String(length=10), nullable=False),
    sa.Column('connection_status', sa.String(length=10), nullable=False),
    sa.Column('last_telemetry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elevators_building_id'), 'elevators', ['building_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_inferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(length=30), nullable=False),
    sa.Column('fault_detected', sa.Boolean(), nullable=False),
    sa.Column('fault_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('inference_time_ms', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_inferences_elevator_created', 'ai_inferences', ['elevator_id', 'created_at'], unique=False)
    op.create_table('alert_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(length=30), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_devices_elevator_id'), 'devices', ['elevator_id'], unique=False)
    op.create_table('elevator_health_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(length=30), nullable=False),
    sa.Column('overall_health', sa.Float(), nullable=False),
    sa.Column('motor_health', sa.Float(), nullable=False),
    sa.Column('bearing_health', sa.Float(), nullable=False),
    sa.Column('door_health', sa.Float(), nullable=False),
    sa.Column('brake_health', sa.Float(), nullable=False),
    sa.Column('electrical_health', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictive_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(length=30), nullable=False),
    sa.Column('failure_risk', sa.Float(), nullable=False),
    sa.Column('rul_hours', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('recommended_action', sa.String(length=300), nullable=False),
    sa.Column('component_health', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(length=30), nullable=False),
    sa.Column('sensor_key', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_lookup', 'sensor_readings', ['elevator_id', 'sensor_key', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role_title', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('active_workload', sa.Integer(), nullable=False),
    sa.Column('current_task_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('completed_task_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('threshold_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_key', sa.String(length=30), nullable=False),
    sa.Column('warning_value', sa.Float(), nullable=False),
    sa.Column('critical_value', sa.Float(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_key')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('notify_critical', sa.Boolean(), nullable=False),
    sa.Column('notify_warning', sa.Boolean(), nullable=False),
    sa.Column('notify_info', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('elevator_id', sa.String(length=30), nullable=False),
    sa.Column('building_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('fault_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('technician_name', sa.String(length=150), nullable=True),
    sa.Column('ai_recommendation', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rca_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elevator_id', sa.String(length=30), nullable=False),
    sa.Column('inference_id', sa.Integer(), nullable=True),
    sa.Column('root_cause', sa.String(length=300), nullable=False),
    sa.Column('affected_component', sa.String(length=150), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('verification_steps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ),
    sa.ForeignKeyConstraint(['inference_id'], ['ai_inferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rca_results')
    op.drop_table('maintenance_tasks')
    op.drop_table('user_preferences')
    op.drop_table('threshold_configs')
    op.drop_table('technicians')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_lookup', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_table('predictive_records')
    op.drop_table('elevator_health_records')
    op.drop_index(op.f('ix_devices_elevator_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_audit_logs_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('alert_records')
    op.drop_index('ix_ai_inferences_elevator_created', table_name='ai_inferences')
    op.drop_table('ai_inferences')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_elevators_building_id'), table_name='elevators')
    op.drop_table('elevators')
    op.drop_table('sensor_definitions')
    op.drop_table('roles')
    op.drop_table('buildings')
    # ### end Alembic commands ###
